name: Build dylib

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Compile dylib
        run: |
          clang -dynamiclib -arch arm64 \
          -isysroot $(xcrun --sdk iphoneos --show-sdk-path) \
          -framework UIKit -framework Foundation \
          menu.m -o ModernMenu.dylib

      - name: Upload dylib
        uses: actions/upload-artifact@v4
        with:
          name: compiled-dylib
          path: ModernMenu.dylib
